/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  InventoryTransaction as PrismaInventoryTransaction,
  Product as PrismaProduct,
} from "@prisma/client";

export class InventoryTransactionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.InventoryTransactionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.inventoryTransaction.count(args);
  }

  async inventoryTransactions(
    args: Prisma.InventoryTransactionFindManyArgs
  ): Promise<PrismaInventoryTransaction[]> {
    return this.prisma.inventoryTransaction.findMany(args);
  }
  async inventoryTransaction(
    args: Prisma.InventoryTransactionFindUniqueArgs
  ): Promise<PrismaInventoryTransaction | null> {
    return this.prisma.inventoryTransaction.findUnique(args);
  }
  async createInventoryTransaction(
    args: Prisma.InventoryTransactionCreateArgs
  ): Promise<PrismaInventoryTransaction> {
    return this.prisma.inventoryTransaction.create(args);
  }
  async updateInventoryTransaction(
    args: Prisma.InventoryTransactionUpdateArgs
  ): Promise<PrismaInventoryTransaction> {
    return this.prisma.inventoryTransaction.update(args);
  }
  async deleteInventoryTransaction(
    args: Prisma.InventoryTransactionDeleteArgs
  ): Promise<PrismaInventoryTransaction> {
    return this.prisma.inventoryTransaction.delete(args);
  }

  async getProduct(parentId: string): Promise<PrismaProduct | null> {
    return this.prisma.inventoryTransaction
      .findUnique({
        where: { id: parentId },
      })
      .product();
  }
}
