/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { InventoryTransaction } from "./InventoryTransaction";
import { InventoryTransactionCountArgs } from "./InventoryTransactionCountArgs";
import { InventoryTransactionFindManyArgs } from "./InventoryTransactionFindManyArgs";
import { InventoryTransactionFindUniqueArgs } from "./InventoryTransactionFindUniqueArgs";
import { CreateInventoryTransactionArgs } from "./CreateInventoryTransactionArgs";
import { UpdateInventoryTransactionArgs } from "./UpdateInventoryTransactionArgs";
import { DeleteInventoryTransactionArgs } from "./DeleteInventoryTransactionArgs";
import { Product } from "../../product/base/Product";
import { InventoryTransactionService } from "../inventoryTransaction.service";
@graphql.Resolver(() => InventoryTransaction)
export class InventoryTransactionResolverBase {
  constructor(protected readonly service: InventoryTransactionService) {}

  async _inventoryTransactionsMeta(
    @graphql.Args() args: InventoryTransactionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [InventoryTransaction])
  async inventoryTransactions(
    @graphql.Args() args: InventoryTransactionFindManyArgs
  ): Promise<InventoryTransaction[]> {
    return this.service.inventoryTransactions(args);
  }

  @graphql.Query(() => InventoryTransaction, { nullable: true })
  async inventoryTransaction(
    @graphql.Args() args: InventoryTransactionFindUniqueArgs
  ): Promise<InventoryTransaction | null> {
    const result = await this.service.inventoryTransaction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => InventoryTransaction)
  async createInventoryTransaction(
    @graphql.Args() args: CreateInventoryTransactionArgs
  ): Promise<InventoryTransaction> {
    return await this.service.createInventoryTransaction({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => InventoryTransaction)
  async updateInventoryTransaction(
    @graphql.Args() args: UpdateInventoryTransactionArgs
  ): Promise<InventoryTransaction | null> {
    try {
      return await this.service.updateInventoryTransaction({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => InventoryTransaction)
  async deleteInventoryTransaction(
    @graphql.Args() args: DeleteInventoryTransactionArgs
  ): Promise<InventoryTransaction | null> {
    try {
      return await this.service.deleteInventoryTransaction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(
    @graphql.Parent() parent: InventoryTransaction
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
