/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InventoryTransactionService } from "../inventoryTransaction.service";
import { InventoryTransactionCreateInput } from "./InventoryTransactionCreateInput";
import { InventoryTransaction } from "./InventoryTransaction";
import { InventoryTransactionFindManyArgs } from "./InventoryTransactionFindManyArgs";
import { InventoryTransactionWhereUniqueInput } from "./InventoryTransactionWhereUniqueInput";
import { InventoryTransactionUpdateInput } from "./InventoryTransactionUpdateInput";

export class InventoryTransactionControllerBase {
  constructor(protected readonly service: InventoryTransactionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: InventoryTransaction })
  async createInventoryTransaction(
    @common.Body() data: InventoryTransactionCreateInput
  ): Promise<InventoryTransaction> {
    return await this.service.createInventoryTransaction({
      data: {
        ...data,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,
        transactionDate: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [InventoryTransaction] })
  @ApiNestedQuery(InventoryTransactionFindManyArgs)
  async inventoryTransactions(
    @common.Req() request: Request
  ): Promise<InventoryTransaction[]> {
    const args = plainToClass(InventoryTransactionFindManyArgs, request.query);
    return this.service.inventoryTransactions({
      ...args,
      select: {
        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,
        transactionDate: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: InventoryTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async inventoryTransaction(
    @common.Param() params: InventoryTransactionWhereUniqueInput
  ): Promise<InventoryTransaction | null> {
    const result = await this.service.inventoryTransaction({
      where: params,
      select: {
        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,
        transactionDate: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: InventoryTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInventoryTransaction(
    @common.Param() params: InventoryTransactionWhereUniqueInput,
    @common.Body() data: InventoryTransactionUpdateInput
  ): Promise<InventoryTransaction | null> {
    try {
      return await this.service.updateInventoryTransaction({
        where: params,
        data: {
          ...data,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          quantity: true,
          transactionDate: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: InventoryTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInventoryTransaction(
    @common.Param() params: InventoryTransactionWhereUniqueInput
  ): Promise<InventoryTransaction | null> {
    try {
      return await this.service.deleteInventoryTransaction({
        where: params,
        select: {
          createdAt: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          quantity: true,
          transactionDate: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
